---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: test
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: clone-repo
        image: alpine/git:1.0.4
        securityContext:
          runAsUser: 1000
        command: ["/bin/sh", "-c", "git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.org/khinkali/keycloak_backup_test /opt/jboss/keycloak/standalone/data"]
        volumeMounts:
        - name: keycloak-home
          mountPath: /opt/jboss/keycloak/standalone/data
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: password
      containers:
      - name: keycloak
        image: khinkali/keycloak:todo
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_password
        - name: KAFKA_ADDRESS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-home
          mountPath: /opt/jboss/keycloak/standalone/data
      volumes:
      - name: keycloak-home
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: test
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31190
  type: NodePort
